# Generated by Django 5.1.7 on 2025-03-16 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source_F',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('construction', 'Construction'), ('réhabilitation', 'Réhabilitation'), ('suivi_présence_des_enseignants', 'Suivi présence des enseignants'), ('Activités_de_sensibilisation', 'Activités de sensibilisation'), ('cantine', 'Cantine'), ('autres', 'Autres')], max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='local',
            name='affectation_du_local',
        ),
        migrations.RemoveField(
            model_name='local',
            name='dont',
        ),
        migrations.RemoveField(
            model_name='local',
            name='etat_fenetres',
        ),
        migrations.RemoveField(
            model_name='local',
            name='etat_murs',
        ),
        migrations.RemoveField(
            model_name='local',
            name='etat_portes',
        ),
        migrations.RemoveField(
            model_name='local',
            name='etat_sol',
        ),
        migrations.RemoveField(
            model_name='local',
            name='etat_toit',
        ),
        migrations.RemoveField(
            model_name='local',
            name='nature_murs',
        ),
        migrations.RemoveField(
            model_name='local',
            name='nature_sol',
        ),
        migrations.RemoveField(
            model_name='local',
            name='nature_toit',
        ),
        migrations.DeleteModel(
            name='SourceFinancement',
        ),
        migrations.AlterField(
            model_name='local',
            name='source_financement',
            field=models.ManyToManyField(help_text="Sélectionnez jusqu'à une source.", related_name='local', to='app.source_f'),
        ),
        migrations.DeleteModel(
            name='Affectation',
        ),
        migrations.AddField(
            model_name='local',
            name='affectation_du_local',
            field=models.CharField(blank=True, choices=[('salle_classe_utilisée', 'Salle de classe utilisée'), ('salle_classe_non_utilisée', 'Salle de classe  non utilisée'), ('magasin_pédagogique', 'Magasin pédagogique'), ('magasin_alimentaire', 'Magasin alimentaire'), ('Bureau directeur', 'Bureau directeur'), ('Logement', 'Logement'), ('Réfectoire', 'Réfectoire')], max_length=250, null=True),
        ),
        migrations.DeleteModel(
            name='Dont',
        ),
        migrations.AddField(
            model_name='local',
            name='dont',
            field=models.CharField(blank=True, choices=[('salle_autre_école', 'Salle autre école'), ('local_emprunté_Loué', 'Local emprunté/Loué')], max_length=250, null=True),
        ),
        migrations.DeleteModel(
            name='EtatFenetre',
        ),
        migrations.AddField(
            model_name='local',
            name='etat_fenetres',
            field=models.CharField(blank=True, choices=[('bon', 'Bon'), ('mauvais', 'mauvais'), ('non installée', 'Non installée')], max_length=250, null=True),
        ),
        migrations.DeleteModel(
            name='EtatMurs',
        ),
        migrations.AddField(
            model_name='local',
            name='etat_murs',
            field=models.CharField(blank=True, choices=[('bon_acceptable', 'Bon / acceptable'), ('mauvais', 'Mauvais')], max_length=250, null=True),
        ),
        migrations.DeleteModel(
            name='EtatPortes',
        ),
        migrations.AddField(
            model_name='local',
            name='etat_portes',
            field=models.CharField(blank=True, choices=[('bon', 'Bon'), ('mauvais', 'mauvais'), ('non installée', 'Non installée')], max_length=250, null=True),
        ),
        migrations.DeleteModel(
            name='EtatSol',
        ),
        migrations.AddField(
            model_name='local',
            name='etat_sol',
            field=models.CharField(blank=True, choices=[('bon_acceptable', 'Bon / acceptable'), ('mauvais', 'Mauvais')], max_length=250, null=True),
        ),
        migrations.DeleteModel(
            name='EtatToit',
        ),
        migrations.AddField(
            model_name='local',
            name='etat_toit',
            field=models.CharField(blank=True, choices=[('bon_acceptable', 'Bon / acceptable'), ('mauvais', 'Mauvais')], max_length=250, null=True),
        ),
        migrations.DeleteModel(
            name='NatureMurs',
        ),
        migrations.AddField(
            model_name='local',
            name='nature_murs',
            field=models.CharField(blank=True, choices=[('endur', 'En dur'), ('semi_dur', 'Semi dur'), ('banco', 'Banco'), ('Paillotes', 'Paillotes'), ('autres', 'Autres')], max_length=250, null=True),
        ),
        migrations.DeleteModel(
            name='NatureSol',
        ),
        migrations.AddField(
            model_name='local',
            name='nature_sol',
            field=models.CharField(blank=True, choices=[('ciment', 'Ciment'), ('terre', 'Terre'), ('autre', 'Autre')], max_length=250, null=True),
        ),
        migrations.DeleteModel(
            name='NatureToit',
        ),
        migrations.AddField(
            model_name='local',
            name='nature_toit',
            field=models.CharField(blank=True, choices=[('dur', 'Dur'), ('tôle', 'Tôle'), ('chaume', 'Chaume'), ('autres', 'Autres')], max_length=250, null=True),
        ),
    ]
