# Generated by Django 5.1.7 on 2025-03-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ecole_identification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_code', models.CharField(blank=True, max_length=50, null=True)),
                ('nouveau_code', models.CharField(blank=True, max_length=50, null=True)),
                ('nom', models.CharField(max_length=200)),
                ('ancien_nom', models.CharField(blank=True, max_length=200, null=True)),
                ('date_creation', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(blank=True, choices=[('public', 'Public'), ('prive', 'Privé')], max_length=20, null=True)),
                ('zone', models.CharField(blank=True, choices=[('rurale', 'Rurale'), ('urbaine', 'Urbaine')], max_length=20, null=True)),
                ('wilaya', models.CharField(blank=True, max_length=200, null=True)),
                ('moughataa', models.CharField(blank=True, max_length=200, null=True)),
                ('commune', models.CharField(blank=True, max_length=200, null=True)),
                ('localite', models.CharField(blank=True, max_length=200, null=True)),
                ('dren', models.CharField(blank=True, max_length=200, null=True)),
                ('iden', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
