# Generated by Django 5.1.7 on 2025-03-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecole_identification',
            name='commune',
        ),
        migrations.RemoveField(
            model_name='ecole_identification',
            name='dren',
        ),
        migrations.RemoveField(
            model_name='ecole_identification',
            name='iden',
        ),
        migrations.RemoveField(
            model_name='ecole_identification',
            name='localite',
        ),
        migrations.RemoveField(
            model_name='ecole_identification',
            name='moughataa',
        ),
        migrations.RemoveField(
            model_name='ecole_identification',
            name='wilaya',
        ),
        migrations.AddField(
            model_name='ecole_identification',
            name='Localisation_administrative',
            field=models.CharField(blank=True, choices=[('wilaya', 'Wilaya'), ('moughataa', 'Moughataa'), ('commune', 'Commune'), ('localite', 'Localite')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ecole_identification',
            name='Localisation_scolaire',
            field=models.CharField(blank=True, choices=[('dren', 'dren'), ('iden', 'iden')], max_length=20, null=True),
        ),
    ]
