# Generated by Django 5.1.7 on 2025-03-13 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_ecole_activites_ape_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecole',
            name='activites_ape',
        ),
        migrations.DeleteModel(
            name='Activite_APE',
        ),
        migrations.AddField(
            model_name='ecole',
            name='activites_ape',
            field=models.CharField(blank=True, choices=[('construction', 'Construction'), ('réhabilitation', 'Réhabilitation'), ('suivi_présence_des_enseignants', 'Suivi présence des enseignants'), ('activités_de_sensibilisation', 'Activités de sensibilisation'), ('cantine', 'Cantine'), ('autres', 'Autres')], max_length=250, null=True),
        ),
    ]
