# Generated by Django 5.1.7 on 2025-03-13 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_ecole_activites_ape_delete_activite_ape_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activite_APE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('construction', 'Construction'), ('réhabilitation', 'Réhabilitation'), ('suivi_présence_des_enseignants', 'Suivi présence des enseignants'), ('Activités_de_sensibilisation', 'Activités de sensibilisation'), ('cantine', 'Cantine'), ('autres', 'Autres')], max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ecole',
            name='activites_ape',
        ),
        migrations.AddField(
            model_name='ecole',
            name='activites_ape',
            field=models.ManyToManyField(help_text="Sélectionnez jusqu'à trois activités.", related_name='ecoles', to='app.activite_ape'),
        ),
    ]
