# Generated by Django 5.1.7 on 2025-03-13 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_activite_ape_remove_ecole_activites_ape_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecole_identification',
            name='ancien_code',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ecole_identification',
            name='nouveau_code',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
    ]
