# Generated by Django 5.1.7 on 2025-03-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_affec_do_etatfenetre_etatmur_etatporte_etatsol_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobilierCollectif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('etat', models.CharField(choices=[('bon_acceptable', 'Bon / acceptable'), ('mauvais', 'Mauvais')], max_length=20)),
                ('nombre', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MobilierEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_table_banc', models.CharField(choices=[('1_place', '1 place'), ('2_places', '2 places'), ('4_places', '4 places')], max_length=10)),
                ('etat', models.CharField(choices=[('bon_acceptable', 'Bon / acceptable'), ('mauvais', 'Mauvais')], max_length=20)),
                ('nombre', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='MobilierEtEquipements',
        ),
    ]
